### ISSUE TITLE
Kubectl apply -f <folder> returns an error message even though deployment was successful.

### ISSUE THREAD

**Issue by Ogala** [jenkinsci/google-kubernetes-engine-plugin#73]
When passed manifest as a folder, deployment proceeds to completion - verifiable from GCP-K8s, yet it returns an error message. Happens with `verifyDeployments: true`  and `verifyDeployments: false`.

Deploy step: `step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, zone: env.ZONE, manifestPattern: 'k8s', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])`

K8s is a folder containing manifest files. 

Error Message: 

`$ kubectl --kubeconfig /var/jenkins_home/workspace/<service>/.kube7872525573563587802config apply -f /var/jenkins_home/workspace/Exhibitor-Service/k8s
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.io.IOException: Failed to launch command args: [kubectl, --kubeconfig, /var/jenkins_home/workspace/<service>/.kube7872525573563587802config, apply, -f, /var/jenkins_home/workspace/<service>/k8s], status: 1
	at com.google.jenkins.plugins.k8sengine.KubectlWrapper.launchAndJoinCommand(KubectlWrapper.java:137)
	at com.google.jenkins.plugins.k8sengine.KubectlWrapper.runKubectlCommand(KubectlWrapper.java:113)
	at com.google.jenkins.plugins.k8sengine.KubernetesEngineBuilder.perform(KubernetesEngineBuilder.java:207)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE`

**Comment by craigatgoogle** [comment]
Thanks @Ogala for reporting this! Will dig into it and see what's going on.

**Comment by Ogala** [comment]
I upgraded to `v 0,5.0` and the issue seems to resolved. Closing the issue.

**Comment by craigatgoogle** [comment]
Glad to hear it. Thanks!

**Comment by kotalakshman** [comment]
> I upgraded to `v 0.5.0` and the issue seems to resolved. Closing the issue.

Hi ! iam facing the same issue, may I know the solution regarding this!!!!!!

**Comment by devopschn** [comment]
> Author

which version want to upgrade????
